### ISSUE TITLE
Cat Fish NPC

### ISSUE THREAD

**Issue by QuercusFelis** [wetfish/online#123]
All these items + wearing fish mask
[catfish.zip](https://github.com/wetfish/online/files/4700162/catfish.zip)

should look something like this
[https://wiki.wetfish.net/upload/3ba5df0b-4d1c-2d80-ea90-1cf700085622.png](https://wiki.wetfish.net/upload/3ba5df0b-4d1c-2d80-ea90-1cf700085622.png)

**Comment by itsrachelfish** [comment]
Description text

>H-hey there big boy... I'm definitely a 100% real fish who totally wants to date you!!! Haha, do you kiss on the first date??? :3c
>
>I'm bored, c'mon let's go somewhere more private~
>
>*Nyaaa*—uhh umm, I mean *blub* *blub* hehe, there I go just me bein' a fish again XD

**Comment by itsrachelfish** [comment]
**Some of these items already exist:**
Cat ears - 2000 (current price)
:3 face - 4800 (WOW SO EXPENSIVE)
Spooky fish mask - 0 (this should probably be edited to cost 1000 or something?)

**New items:**
Cat skin - 10,000 coral
Nose & Whiskers - 500
Cat toy - 500
Collar - 1000
Fish sign - 500
Ocean background - 5000
