### ISSUE TITLE
/me

### ISSUE THREAD

**Issue by ghost** [wetfish/online#74]
![me](https://cloud.githubusercontent.com/assets/17911663/21106038/24d9aaac-c052-11e6-85f1-a91ef0a1ed71.png)

Selected via drop down button.
Username is not prefilled into example text "Kitlero wraps a wet noodle around **lemonrising's** finger" it must be manually keyed in.

**Comment by itsrachelfish** [comment]
I don't see what this would be used for besides roleplaying, which nobody uses the forums for. :woman_shrugging:
