### ISSUE TITLE
TIP LIST

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/online#88]
There should be a new page which lists recent tips, the top daily, and top weekly tips.

It would display the post in full, along with the avatar, the total amount tipped, and a permalink to the thread itself.

That's a lot of information for a single page, so maybe there should be a tabbed interface or at least links to change which list you're viewing.

**Comment by QuercusFelis** [comment]
i want to see all the posts ive donated coral to

**Comment by itsrachelfish** [comment]
@woodcat69 this is a feature now! You can search from the tip list page
